dependencies:
- alias: activiti-cloud
  name: activiti-cloud-full-example
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.3.0
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
